EMBARGO: int = 8

TEST_ERA_1: int = 1176
TEST_ERA_0: int = 1133

VALIDATION_ERA_1: int = TEST_ERA_1
VALIDATION_ERA_0: int = TEST_ERA_0

TRAIN_ERA_1: int = VALIDATION_ERA_0 - EMBARGO
TRAIN_ERA_0: int = 1
